Fix 5856 for Export-DbaRegServer
sqlcollaborative/dbatools pull request #6939
Opened 2020-10-25 22:42 UTC by lancasteradam

- Fixes #5856 by ensuring -FilePath is implemented
- Added -Group and -ExcludeGroup params
- Changed the command to allow for either .xml or .regsrvr file extensions
- Updated documentation for the new params
- Added more integration tests
- Fixed the implementation of -ExcludeGroup in Get-DbaRegServerGroup
- Fixed the Disconnect call in Add-DbaRegServerGroup

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #5856  )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [x] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
 
See comments above.

### Commands to test

See the pester test files.

### Learning

Helpful resource:
https://4sysops.com/archives/validating-file-and-folder-paths-in-powershell-parameters/

2020-10-25 23:39 UTC, lancasteradam commented
The tests for the code involved in this PR have completed successfully. The errors seem to be from Get-DbaDbSharePoint.

2020-10-26 08:34 UTC, potatoqualitee commented
Thanks so much! Re-running tests and will examine shortly.

2020-10-26 08:55 UTC, potatoqualitee commented
this looks fantastic to me! thank you so much. the additional tests are much appreciated. @ClaudioESSilva, any chance you can take a look and approve as well?

2020-10-26 08:59 UTC, potatoqualitee commented
actually, i do see one issue. will comment now 👍

2020-10-26 09:03 UTC, potatoqualitee requested changes

2020-10-26 09:03 UTC, potatoqualitee commented on functions/Export-DbaRegServer.ps1
> +                throw [System.Management.Automation.RuntimeException] "Use the -Overwrite parameter if the file $FilePath should be overwritten."
We use an internal command, `Stop-Function`, in place of throws. `Stop-Function` is user friendly in appearance and also does additional logging behind the scenes.

```suggestion
                Stop-Function -Message "Use the -Overwrite parameter if the file $FilePath should be overwritten."
                return
```

2020-10-26 09:03 UTC, potatoqualitee commented on functions/Export-DbaRegServer.ps1
> +                    throw "The FilePath specified must end with either .xml or .regsrvr"
Please perform validation within the `begin` block and use `Stop-Function` in place of `throw` 🙇

2020-10-26 15:48 UTC, lancasteradam commented
ok, sounds good. I'll make those changes.

2020-10-30 08:03 UTC, potatoqualitee commented
Should be done today 💯

2020-10-31 09:39 UTC, potatoqualitee commented
let's do this 😅 !

2020-10-31 09:40 UTC, merged