Add config item to bypass CredSSP initialization
sqlcollaborative/dbatools pull request #7150
Opened 2021-02-19 19:03 UTC by kozloski

* add configuration setting "commands.initialize-credssp.bypass"
* add check for configuration item value in Initialize-CredSSP function,
  log message and return if true

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [X] New feature (non-breaking change, adds functionality, fixes #7148 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [ ] Documentation
 - [ ] Build system
 

### Purpose
Add a configuration item to bypass initialization of CredSSP configuration. This can be useful in cases where the user is not allowed to configure CredSSP on their computer or servers, or where a user already has CredSSP configured and does not want the existing configuration to be altered.

### Approach
Add a configuration item "commands.initialize-credssp.bypass" with a default value of $false to internal/configurations/settings/commands.ps1 

In internal/functions/Initialize-CredSSP.ps1, add a check for this configuration value.
If true, log a message indicating CredSSP initialization is bypassed, and return from the function with no further action.

2021-02-19 21:17 UTC, nvarscar commented
See https://github.com/sqlcollaborative/dbatools/issues/7148#issuecomment-782357926

2021-02-21 21:39 UTC, nvarscar requested changes
Please add information about this setting to the Description of the public functions (install/update-dbainstance), so that users are aware how to use it.

2021-02-22 18:24 UTC, nvarscar approved these changes
Looks good

2021-03-11 09:48 UTC, potatoqualitee commented
woo! thank you, @nvarscar! And thank you so much for the contribution, @kozloski

2021-03-11 09:49 UTC, merged