New command for adding a linked server
sqlcollaborative/dbatools pull request #7392
Opened 2021-05-31 15:55 UTC by lancasteradam

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [ ] Nunit test is included
 - [x] Documentation
 - [ ] Build system
 

### Purpose
 
Basic command to add a new linked server.

### Commands to test

See the integration tests.

2021-05-31 15:57 UTC, andreasjordan commented
So this will be part of #6506?

2021-05-31 16:02 UTC, lancasteradam commented
Hi @andreasjordan, I had not seen that issue, but yes I will update the description of this PR and the other one I just added for removing a linked server so that they both reference 6506.

Thanks,
Adam

2021-05-31 16:04 UTC, andreasjordan commented
There is also this one: #6196

2021-05-31 16:07 UTC, lancasteradam commented
When I tried the "set" workflow SMO displayed an error message indicating that the linked server has to be dropped and recreated.

2021-05-31 16:09 UTC, andreasjordan commented
Ok, then maybe you can add the messages to the feature request and close it.

2021-05-31 16:22 UTC, potatoqualitee commented
Looks nice! Any chance you can add a LoginCredential or something similarly named and allow them to create a Linked Server login?

![image](https://user-images.githubusercontent.com/8278033/120220420-fdfd6300-c23c-11eb-87d1-5fd6258df16f.png)

If it's too much work, we can add it later.

2021-05-31 17:44 UTC, lancasteradam commented
@potatoqualitee, would it be ok to accept the current scope of this PR as a phase 1? I could come back to the login piece at a later date as a phase 2. I would want to proceed very carefully on that part because of the need for secure credential handling.

@andreasjordan, I added the comment to #6196, but I don't have permission to close issues.

2021-06-11 06:16 UTC, andreasjordan requested changes

2021-06-11 06:16 UTC, andreasjordan commented on functions/New-DbaLinkedServer.ps1
> +                    $newLinkedServer
Please use Get-DbaLinkedServer to get a nice object with the custom properties for the new linked server:
```
$instance |  Get-DbaLinkedServer -LinkedServer $LinkedServer
```

2021-06-11 06:16 UTC, andreasjordan commented on functions/New-DbaLinkedServer.ps1
> +        foreach ($instance in $InputObject) {
If something is a server SMO with an active connection, so the output of Connect-DbaInstance, we call this $server. And there are definitly server SMOs in $InputObject so I would change this line to 
```
foreach ($server in $SqlInstance) {
```

2021-06-14 00:50 UTC, lancasteradam commented
Thank you @potatoqualitee and @andreasjordan. I've incorporated the feedback mentioned by @andreasjordan.

2021-06-14 05:32 UTC, andreasjordan approved these changes

2021-06-14 07:18 UTC, andreasjordan commented
Approved both pull request.

2021-06-18 12:25 UTC, merged

2021-06-18 12:25 UTC, potatoqualitee commented
Fantastic 💯 !