New command: New-DbaLinkedServerLogin
sqlcollaborative/dbatools pull request #7983
Opened 2021-11-24 17:43 UTC by lancasteradam

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #7982 )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [x] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [x] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/sqlcollaborative/appveyor-lab ?
 - [x] Unit test is included
 - [x] Documentation
 - [ ] Build system

### Purpose

Adding a new command for a login to be added to a linked server.

This is the 3rd in a series of PRs related to linked servers:

1. Update for Remove-DbaLinkedServer (PR 7952, already merged)
2. New command for Get-DbaLinkedServerLogin	(PR 7965, already merged)
3. New command for New-DbaLinkedServerLogin (This PR)
4. New command for Remove-DbaLinkedServerLogin
5. Update for New-DbaLinkedServer
6. New command for Set-DbaLinkedServer

### Approach

Basic command to accept the param values for a linked server login and then update the linked server.

### Commands to test

See the examples and the pester tests.

2021-12-07 10:10 UTC, potatoqualitee requested changes
thanks again 🙇🏼

2021-12-07 10:10 UTC, potatoqualitee commented on functions/New-DbaLinkedServerLogin.ps1
> +                Stop-Function -Message "LinkedServer is required"
Thank you, Adam! This should go before the foreach so that it only processes once.

2021-12-07 10:10 UTC, potatoqualitee commented on functions/New-DbaLinkedServerLogin.ps1
> +            $InputObject += Connect-DbaInstance -SqlInstance $instance -SqlCredential $SqlCredential | Get-DbaLinkedServer -LinkedServer $LinkedServer
Interesting! We generally do `Get-DbaLinkedServer -SqlInstance $instance -SqlCredential $SqlCreential -LinkedServer $LinkedServer` Is there a benefit to the pipe?

2021-12-07 10:10 UTC, potatoqualitee commented on functions/New-DbaLinkedServerLogin.ps1
> +        [string]$LocalLogin,
None of these are mandatory. What happens when someone doesn't specify anything? If it does nothing, can you do a check in begin or process to ensure they gave at least one of something?

2021-12-08 03:28 UTC, lancasteradam commented
Thanks @potatoqualitee for the feedback, much appreciated. I've made changes to reflect each item above, let me know what you think or if more edits are needed.

2021-12-08 15:28 UTC, potatoqualitee commented
Good stuff! Thank you, will release shortly

2021-12-08 15:29 UTC, merged